api/urls.py
from django.urls import path
from .views import GetParksView


app_name = 'api'

urlpatterns = [
    path('all/', GetParksView.as_view(), name='all'),
]

map/urls.py
from django.urls import path
from .views import Index

app_name = 'map'


urlpatterns = [
    path('', Index.as_view(), name='index'),
]

parks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('map.urls', namespace='map')),
    path('api/', include('api.urls', namespace='api')),
]

api/models.py
import uuid

from django.db import models
from django.db.models import Model
from django.contrib.gis.db import models as gis_models


class Park(Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(
        max_length=100,
        blank=False,
        null=False,
        verbose_name='Название',
        help_text='Название парка'
    )
    address = models.CharField(
        max_length=150
    )
    description = models.TextField(
        max_length=500,
        verbose_name="Описание",
        help_text="Описание парка"
    )
    geofence = gis_models.PolygonField()

    class Meta:
        db_table = 'parks'

map/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Park
from .serializers import ParkSerializer


class GetParksView(APIView):
    def get(self, request):
        queryset = Park.objects.all()

        serializer_for_queryset = ParkSerializer(
            instance=queryset,
            many=True
        )

        return Response(serializer_for_queryset.data)
    

map/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'map/index.html'

map/templates/map/index.html
<!DOCTYPE html>

{% load static %}

<html lang="ru">
    <head>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.css">
        <link rel="stylesheet" href="{% static 'map/css/bootstrap.min.css' %}">
        <style>
            .leaflet-container {
                width: 100%;
                height: 800px;
                position: relative;
            }
            #park-card {
                position: absolute;
                top: 0;
                bottom: 0;
                right: 0;
                width: 350px;
                margin: 1% 5%;
                z-index: 10000;
            }
        </style>
        <title>Главная</title>
    </head>
    <body>
        <header class="navbar navbar-dark" style="background-color: white">
            <div class="container">
                <a class="navbar-brand" style="color: #157347" href="{% url 'map:index' %}">
                    <span>Moscow Parks</span>
                </a>
            </div>
        </header>
        <main>
            <div id="root"></div>
            <script src="{% static 'map/js/main.js' %}"></script>
        </main>
        <footer class="page-footer font-small blue border-top" style="background-color: white">
            <div class="footer-copyright text-center py-3 text-black-50">
                © 2020 Copyright
            </div>
        </footer>
    </body>
</html>